services:
  postgres:
    build:
      context: .
      dockerfile: dockerfiles/postgres/Dockerfile
      args:
        POSTGRES_VERSION: 14
        POSTGRES_PORT: ${POSTGRES_PORT}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
    env_file:
      - .env
    networks:
      - database
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "$DBT_USER", "-d", "$DBT_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  dbt-xray:
    build:
      context: .
      dockerfile: dockerfiles/dbt-xray/Dockerfile
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
    networks:
      - database
    depends_on:
      postgres:
        condition: service_healthy
  
networks:
  database:
    driver: bridge
    
